# Project #1 Detecting Patterns in Tabular Medical Data with MIMIC-III
You can read more about the dataset here: https://www.kaggle.com/datasets/saurabhshahane/in-hospital-mortality-prediction

Dr. Barak Or

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
my_path="/content/MIMIC_data - MIMIC_data.csv"

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Load the data
data = pd.read_csv(my_path)

In [ ]:
print(data.head())

   group      ID  outcome  age  gendera        BMI  hypertensive  \
0      1  125047      0.0   72        1  37.588179             0
1      1  139812      0.0   75        2        NaN             0
2      1  109787      0.0   83        2  26.572634             0
3      1  130587      0.0   43        2  83.264629             0
4      1  138290      0.0   75        2  31.824842             1

   atrialfibrillation  CHD with no MI  diabetes  ...  Blood sodium  \
0                   0               0         1  ...    138.750000
1                   0               0         0  ...    138.888889
2                   0               0         0  ...    140.714286
3                   0               0         0  ...    138.500000
4                   0               0         0  ...    136.666667

   Blood calcium    Chloride  Anion gap  Magnesium ion     PH  Bicarbonate  \
0       7.463636  109.166667  13.166667       2.618182  7.230    21.166667
1       8.162500   98.444444  11.444444       1.887500  7.225    33.444444
2       8.266667  105.857143  10.000000       2.157143  7.268    30.571429
3       9.476923   92.071429  12.357143       1.942857  7.370    38.571429
4       8.733333  104.500000  15.166667       1.650000  7.250    22.000000

   Lactic acid  PCO2  EF
0          0.5  40.0  55
1          0.5  78.0  55
2          0.5  71.5  35
3          0.6  75.0  55
4          0.6  50.0  55

[5 rows x 51 columns]

In [ ]:
# Calculate descriptive statistics for 'age', 'BMI', and 'Blood sodium'
age_stats = data['age'].agg(['mean', 'median', lambda x: x.mode()[0] if not x.mode().empty else 'N/A', 'std']).rename({'<lambda>': 'mode'})
bmi_stats = data['BMI'].agg(['mean', 'median', lambda x: x.mode()[0] if not x.mode().empty else 'N/A', 'std']).rename({'<lambda>': 'mode'})
sodium_stats = data['Blood sodium'].agg(['mean', 'median', lambda x: x.mode()[0] if not x.mode().empty else 'N/A', 'std']).rename({'<lambda>': 'mode'})

# Display the statistics
print("Age Statistics:")
display(age_stats)

print("\nBMI Statistics:")
display(bmi_stats)

print("\nBlood Sodium Statistics:")
display(sodium_stats)

Age Statistics:

mean      74.055225
median    77.000000
mode      89.000000
std       13.434061
Name: age, dtype: float64

BMI Statistics:

mean      30.188278
median    28.312474
mode      23.296976
std        9.325997
Name: BMI, dtype: float64

Blood Sodium Statistics:

mean      138.890016
median    139.250000
mode      140.000000
std         4.151347
Name: Blood sodium, dtype: float64

# Q1.a
What are the mean, median, mode, and standard deviation of the age, BMI, and Blood sodium columns in the dataset? Why are these statistics important for understanding the data?

# Q1.b
How do the distributions of age, BMI, and Blood sodium look in the dataset? What can we learn from these distributions about the patient population?

# Q 1.c
Use pandas and scikit-learn to drop rows with missing values in the 'BMI' and 'Blood sodium' columns, and then uses logistic regression, SVM, kNN, and decision tree to predict an 'outcome' based on the features 'age', 'BMI', and 'Blood sodium'. Ensure to split the data using train_test_split with a 20% test size and a random state of 42. Finally, fit the model, make predictions on the test set, and print a report of the best model (“classification_report”). Explain the result of the confusion matrix for the best model.

# Q1.d
Predict BMI based on age and Blood sodium with linear regression, SVM regressor, Decision tree regressor, and kNN refressor. Calculate RMSE, MSE, R-squared.
Split where 20% left for the test, random state=42.

# Q2.a

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Q2.b
Apply K-means clustering to the dataset to group patients based on age, BMI, diabetes, and heart rate. Cluster to 2,3,4,5, and 6 groups. What are Silhouette and Davies-Bouldin Score for each case?

#Q3.a
Describe the steps involved in training a neural network, including forward propagation and backpropagation.

## Answer

# Q3.b
Explain the bias-variance trade-off in neural network performance. How does it affect model generalization?

## Answer

# Q3.c
Highlight the importance of data preprocessing, normalization, and splitting for training effective deep learning models.

## Answer

# Q3.d+e

Relevant library from tensorflow

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Ensuring data is clean and ready with all features